# Generated by Django 4.0 on 2021-12-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_strain_delete_strains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
