# Generated by Django 4.0 on 2021-12-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_alter_strain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
