# Generated by Django 4.0 on 2021-12-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_alter_strain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
